version: '3.8'
services:
  postgres:
    container_name: postgresdb
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    container_name: apiserver
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"

volumes:
  postgres: