name: deploy-wer1-backend
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: echo "TODO: Setup Test Database"
      - run: echo "TODO: Setup Prisma"
      - run: echo "TODO: Seed Test Database"
      - run: echo "TODO: Run Tests"
